### ISSUE TITLE
Inserting makes illegal assignments

### ISSUE THREAD

**Issue by vincentmvdm** [darknoon/figma-json-plugin#9]
Repro: try inserting [this JSON](https://gist.github.com/vincentmvdm/3d039c97b2cc27b2cf92cabb047bcee7).

- Warning: backgrounds on groups are no longer supported
- Warning: CENTER is no longer a supported value for layoutAlign
- Error: Can only set itemReverseZIndex on nodes with layoutMode !== NONE'
- Error: Can only set strokesIncludedInLayout on nodes with layoutMode !== NONE'
- Error: Expected layoutGrids to have type "GRID" but got string instead
- Error: First argument to group() must be an array of at least one node

**Comment by darknoon** [comment]
yup, seeing this too
<img width="535" alt="Screenshot 2023-02-16 at 4 06 38 PM" src="https://user-images.githubusercontent.com/355540/219487007-3ac913b5-24d6-4875-9757-dd273d98cf06.png">

**Comment by darknoon** [comment]
I was just trying to dump some layer trees from the Magic Rename Eval doc and re-insert it, which is a decent test case I think
